/**
 * Health Impact Summary (MHIN) — a formal, credible one-page report a user can
 * submit to a college dean or HR to advocate for menstrual leave.
 *
 * computeImpactData() derives the structured JSON from the user's own logs;
 * generateImpactReport() renders the exact six required sections in a formal,
 * factual tone. Never exaggerates, never diagnoses. This is the offline template
 * engine; the server /impact endpoint uses the verbatim MHIN prompt for AI mode.
 */
import { getLogs, getCycleStats, getSymptoms, getProfile } from './localStore'

const SYMPTOM_LABELS = {
  irregular: 'irregular cycles', heavy: 'heavy bleeding', spotting: 'spotting', pelvic_pain: 'pelvic pain',
  acne: 'acne', hirsutism: 'excess hair growth', hair_thinning: 'hair thinning', dark_patches: 'skin changes',
  weight: 'weight changes', cravings: 'food cravings', bloating: 'bloating', mood: 'mood changes',
  fatigue: 'fatigue', sleep: 'sleep disturbance',
}

/** Build the structured data object the report is generated from. */
export function computeImpactData({ anonymized = true, userName = '' } = {}) {
  const logs = getLogs()
  const stats = getCycleStats()
  const painVals = logs.map((l) => l.pain).filter((p) => typeof p === 'number')
  const avgPain = painVals.length ? painVals.reduce((a, b) => a + b, 0) / painVals.length : 0
  const highPainCount = painVals.filter((p) => p >= 7).length

  const cyclesLogged = Math.max(getCycleStatsCycles(stats, logs), 0)
  const avgHighPainDays = cyclesLogged > 0 ? highPainCount / cyclesLogged : highPainCount

  // Top symptoms: tracked PCOS symptoms first, then derived from logs.
  const tracked = Object.keys(getSymptoms())
    .filter((k) => getSymptoms()[k])
    .map((k) => SYMPTOM_LABELS[k] || k)
  const derived = []
  if (logs.some((l) => l.flow === 'heavy')) derived.push('heavy bleeding')
  if (avgPain >= 5) derived.push('painful periods (dysmenorrhoea)')
  if (logs.some((l) => l.fatigue)) derived.push('fatigue')
  if (logs.some((l) => l.mood === 'low' || l.mood === 'anxious')) derived.push('mood changes')
  const topSymptoms = [...new Set([...tracked, ...derived])].slice(0, 3)

  return {
    cycles_logged: cyclesLogged,
    avg_cycle_length: stats.avgCycleLength || 28,
    avg_pain_day1: Math.round(avgPain),
    avg_pain_day2: Math.round(avgPain),
    avg_high_pain_days_per_cycle: Math.round(avgHighPainDays * 10) / 10,
    top_symptoms: topSymptoms.length ? topSymptoms : ['painful periods'],
    anonymized,
    user_name: anonymized ? null : userName || getProfile().name || null,
  }
}

function getCycleStatsCycles(stats, logs) {
  // Prefer logged period starts; fall back to distinct months of check-ins.
  const periods = JSON.parse(localStorage.getItem('mira.periods.v1') || '[]')
  if (periods.length) return periods.length
  const months = new Set(logs.map((l) => (l.date || '').slice(0, 7)).filter(Boolean))
  return months.size
}

/** Render the six-section formal report from the data. */
export function generateImpactReport(data) {
  const date = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })
  const subject = data.anonymized || !data.user_name ? 'The individual' : data.user_name
  const poss = subject === 'The individual' ? "The individual's" : `${subject}'s`
  const impactedPct =
    data.avg_cycle_length > 0
      ? Math.round((data.avg_high_pain_days_per_cycle / data.avg_cycle_length) * 100)
      : 0
  const symptomList = data.top_symptoms.join(', ')

  return {
    title: 'Menstrual Health Impact Summary | Generated by MHIN',
    date,
    label: data.anonymized || !data.user_name ? 'Anonymized Report' : `Prepared for: ${data.user_name}`,
    sections: [
      {
        heading: '1. Summary Statement',
        body: `${subject} has maintained self-reported menstrual health records across ${data.cycles_logged} cycle(s) using MHIN. The logged data indicates recurring menstrual pain, with an average reported pain severity of ${data.avg_pain_day1} out of 10 on the most affected days and an average of ${data.avg_high_pain_days_per_cycle} high-pain day(s) per cycle (pain rated 7 or above). The most frequently reported symptoms are ${symptomList}. This summary presents that self-logged information in a consolidated, factual form.`,
      },
      {
        heading: '2. Data Evidence',
        body: [
          `• Cycles tracked: ${data.cycles_logged}`,
          `• Average cycle length: ${data.avg_cycle_length} days`,
          `• Average reported pain (most affected days): ${data.avg_pain_day1}/10 (Day 1), ${data.avg_pain_day2}/10 (Day 2)`,
          `• Average high-pain days per cycle (pain ≥ 7): ${data.avg_high_pain_days_per_cycle}`,
          `• Estimated share of cycle days significantly impacted: ${impactedPct}%`,
          `• Most frequently reported symptoms: ${symptomList}`,
        ].join('\n'),
      },
      {
        heading: '3. Functional Impact Statement',
        body: `Published medical literature recognises that moderate-to-severe dysmenorrhoea (menstrual pain) is associated with reduced concentration, temporary decline in academic and occupational performance, and, in many cases, absenteeism on the most affected days. Symptoms of the severity and frequency reflected in ${poss} self-logged data are of the kind that can, in general terms, impair attendance, focus, and routine physical function during the affected days of each cycle. This statement reflects general medical context and does not assert a personal medical conclusion.`,
      },
      {
        heading: '4. Request Statement',
        body: `On the basis of the consolidated self-logged information above, it is respectfully requested that the relevant academic or workplace authority consider ${poss} eligibility for menstrual leave or a comparable flexible-attendance accommodation on the limited number of high-impact days indicated per cycle. Such consideration would support continued participation and performance while accommodating a recurring, well-documented health need. Supporting records are available on request.`,
      },
      {
        heading: '5. Disclaimer',
        body: 'This summary is generated from self-reported data logged by the user over multiple cycles. It is not a clinical diagnosis. For medical evaluation, consult a qualified gynecologist.',
      },
    ],
  }
}

export function impactToText(report) {
  const lines = [report.title, report.date, report.label, '']
  for (const s of report.sections) lines.push(s.heading, s.body, '')
  lines.push('— Generated by MHIN')
  return lines.join('\n')
}
